### ISSUE TITLE
ParameterArgumentValidationError,New-Win32App.ps1

### ISSUE THREAD

**Issue by napitmgmt** [MSEndpointMgr/IntuneAppFactoryResources#1]
Hello!
Not shure if this is a bug or config error, and first of all thank you for this fantastic tool! Can't wait to get it running.
And I know it works since i watched a live demo at the NIC Cloud Connect conference 2023. ty @NickolajA

I'm running the pipeline with the included apps in the "default" repo (7-Zip and Notepad++) 
No custom apps added. This is from my initial setup/test.
Followed the [setup guide](https://msendpointmgr.com/intune-app-factory/#41-repository-files-and-folder) to the letter apart from renaming the KeyVault variables and the DevOps Agent pool name. (I have also renamed them in the publish.yml file)
Pipeline is running on a VM in Azure with custom agent as recommended.
Pipeline runs fine all the way incl. archiving, exept at the last step of **publish__apps**. 

```powershell
New-Win32App script fails with: System.IO.IOException: The handle is invalid.
```

**DevOps agent info:**
Edition	Windows 11 Pro
Version	23H2
Installed on	‎1/‎9/‎2024
OS build	22631.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0

_$PSVersionTable.PSVersion_
Major  Minor  Build  Revision
5      1      22621  2506

_Get-InstalledModule_
Version         Name                                   Repository   
2.15.0           Az.Accounts                         PSGallery            
6.14.0           Az.Resources                        PSGallery         
6.1.0             Az.Storage                            PSGallery            
2312.878      Evergreen                             PSGallery            
1.4.3             IntuneWin32App                  PSGallery         
4.37.0.0        MSAL.PS                                PSGallery            
1.1.4             MSGraphRequest                  PSGallery

_winget -v_
v1.6.3482

**Error:**
```powershell
Reading contents from: C:\ADOAgent\_work\1\a\AppsPublishList\AppsPublishList.json
[APPLICATION: 7-Zip] - Initializing
Using Source folder path: C:\ADOAgent\_work\1\Publish\7zip\Source
Using Output folder path: C:\ADOAgent\_work\1\Publish\7zip\Package
Using Scripts folder path: C:\ADOAgent\_work\1\Publish\7zip\Scripts
Using icon file path: C:\ADOAgent\_work\1\Publish\7zip\Icon.png
Creating .intunewin package file from source folder
INFO   Validating parameters
INFO   Validated parameters within 3 milliseconds
INFO   Removing temporary files
ERROR  System.IO.IOException: The handle is invalid.`

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
WARNING: Unable to detect expected 'Deploy-Application.exe.intunewin' file after IntuneWinAppUtil.exe invocation
Creating default requirement rule
Creating additional custom requirement rules
Creating detection rules
Constructing an icon object
Creating Win32 application


C:\ADOAgent\_work\1\s\Scripts\New-Win32App.ps1 : Cannot validate argument on parameter 'FilePath'. Cannot bind 
argument to parameter 'Path' because it is an empty string.
At C:\ADOAgent\_work\_temp\2bfa738f-fa6b-43df-b81c-ff0784ea28ec.ps1:4 char:1
+ . 'C:\ADOAgent\_work\1\s\Scripts\New-Win32App.ps1' -TenantID 37826109 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Win32App.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-Win32App.ps1
 
##[error]PowerShell exited with code '1'.
Finishing: New-Win32App

```

**Comment by napitmgmt** [comment]
Not related, but uppgraded winget to v1.6.3482
issue persists.

**Comment by napitmgmt** [comment]
Found this on the developer community. Looks very similar:
https://developercommunity.visualstudio.com/t/failure-to-run-intunewinapputilexe-on-hosted-devop/1269111
And this, here on GitHub:
https://github.com/MSEndpointMgr/IntuneWin32App/issues/121

**Comment by napitmgmt** [comment]
Temporary solution as suggested by Soolkiki:
https://github.com/MSEndpointMgr/IntuneWin32App/issues/121#issuecomment-1877786048

Just before:
```powershell
$IntuneAppPackage` = New-IntuneWin32AppPackage -SourceFolder $SourceFolder -SetupFile $AppData.PackageInformation.SetupFile -OutputFolder $OutputFolder
```
Added this line only:
```powershell
Invoke-WebRequest -URI "https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/raw/1a00a2a786de646c5fc46d6e1b79988c636e764e/IntuneWinAppUtil.exe" -outfile "$env:TEMP\IntuneWinAppUtil.exe"
```

The Pipeline now works and the apps are published in Intune.

Any suggestsions for a permanet sulotion?
